---
name: Publish to Ansible Galaxy

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Publish Collection
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core
      
      - name: Update version in galaxy.yml
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/^version:.*/version: $VERSION/" galaxy.yml
      
      - name: Build collection
        run: |
          ansible-galaxy collection build
      
      - name: Publish to Ansible Galaxy
        run: |
          ansible-galaxy collection publish *.tar.gz --api-key=${{ secrets.GALAXY_API_KEY }}
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: collection
          path: "*.tar.gz"

